### ISSUE TITLE
Use/enable a more recent version of JamVM (using 1.4.3, current is 1.5.4)

### ISSUE THREAD

**Issue by ensko** [CBCJVM/CBCJVM#5]
I wasn't able to post on the botabll forum somehow, so I'm posting it here as a feture request.
Basically, replace the files in installer/lib (and installer/jvm?) by the new Classpath/JamVM version, compiled for the CBC. Are there reasons this wasn't done yet, or was it just not seen necessary?
If it's the second, I would gladly take it on myself. Since someone has done this with 1.4.3, I'd like to hear what steps are needed for compiling it, or if it's simpler if he did it himself...
- Are there definite reasons against switching? (performance, incompatibilities, missing support for ARM)
- What are the gains through this? (Bugfixes, more complete/more recent API support)

Personally, I would need this because JamVM 1.4.3 does not support the java.util.concurrent APIs which are handy for multithreading. We were able to avoid it until now, but are now using libraries that need these APIs (Drools). For the average user, it would make the Experience of compiling/running code on the development machine and running it on the CBC more similar, which leads to less irritation.

**Comment by bmcdorman** [comment]
It just wasn't that much of a priority, but can and should be done in the near future. It is a real pain to compile. I will be doing some work at KIPR next week and during winter break, so I may be able to get it done before the next Botball season. CBCJVM is now shipping as a part of the official CBC firmware, so having an up-to-date VM is relatively important. Thank you for posting on our github page. I check the forums perhaps once a month, so this is definitely the correct outlet for feature requests. Anything else you want looked at before next season? I'll probably have time to get it done.

bmcdorman@kipr.org

**Comment by ensko** [comment]
I don't think there's anything else I need... unfortunately this one thing is kind of urgent to us (it's part of the feasibility for a project at school and has to be done in about a week...). Unless it takes you less time explaing it to me than it takes to compile it yourself (a few pointers on what resources/compiler settings I need should be enough hopefully), I'll look into it myself and document my steps as I go along. I can then document my steps and commit my work into a branch for you to review.

**Comment by bmcdorman** [comment]
Here are the steps you need to set up a toolchain for the chumby:
http://wiki.chumby.com/index.php/Hacking_Linux_for_chumby

Then you need to build JamVM in that environment. There are a god awful number of dependencies if I remember correctly, which you will also have to compile and install to the environment.

Sorry that I can't fulfill your time requirements. I currently attend a residential high school (The Oklahoma School of Science and Mathematics), and working on CBCJVM or KISS IDE from here is difficult. KISS IDE will be my primary focus during thanksgiving and winter break, but if you are unsuccessful in compiling JamVM I will attempt to do that as well. Please keep me informed of your progress.

Best of luck.

**Comment by ensko** [comment]
Okay, I've committed my first bunch of work in the JamVM-1.5.4 branch. You can take a look at [BuildJamVM.sh](https://github.com/CBCJVM/CBCJVM/blob/JamVM-1.5.4/installer/BuildJamVM.sh)... so far it seems to work (except that somehow the Hello World doesn't run; it tries to load cbccore.motors.Drive... otherwise, it's okay)

**Comment by bmcdorman** [comment]
Looks great! Feel free to merge it in to the master. I'll do it in a few weeks if you don't.

**Comment by ensko** [comment]
hi! Please wait for this for a while! we're at the moment back on 1.4.3 because of a few issues. I'm busy at the moment, but I'll write up some of our experiences once I get time (should be in a week or so I think)

we're thinking of investigating Mono and Dalvik too; I'll keep you tuned if we get any results!

**Comment by bmcdorman** [comment]
Alright. Mono and Dalvik on the CBC? If you have any luck, I'll try and get it integrated in the CBC 3. Thanks for your help!
